//
//  RightSideMenuWorker.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RightSideMenuWorkerLogic {
    func getUser() async -> String
    func logOut()
}

final class RightSideMenuWorker: RightSideMenuWorkerLogic {
    // MARK: - Fields
    
    private var api: APIManager
    
    init(apiManager: APIManager) {
        self.api = apiManager
    }
    
    // MARK: - Methods
    
    func getUser() async -> String {
        await api.getUser()
    }
    func logOut() {
        api.setUserDefaults(value: "Guest", Key: "username")
    }
}
