//
//  RightSideMenuInteractor.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RightSideMenuBusinessLogic
{
//  func doSomething(request: RightSideMenu.Something.Request)
}

protocol RightSideMenuDataStore
{
  //var name: String { get set }
}

class RightSideMenuInteractor: RightSideMenuBusinessLogic, RightSideMenuDataStore
{
  var presenter: RightSideMenuPresentationLogic?
  var worker: RightSideMenuWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RightSideMenu.Something.Request)
  {
//    worker = RightSideMenuWorker()
//    worker?.doSomeWork()
//
//    let response = RightSideMenu.Something.Response()
//    presenter?.presentSomething(response: response)
  }
}
