//
//  RightSideMenuPresenter.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RightSideMenuPresentationLogic
{
//  func presentSomething(response: RightSideMenu.Something.Response)
}

class RightSideMenuPresenter: RightSideMenuPresentationLogic
{
  weak var viewController: RightSideMenuDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: RightSideMenu.Something.Response)
//  {
//    let viewModel = RightSideMenu.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
