//
//  RightSideMenuInteractor.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RightSideMenuBusinessLogic {
    func getUsername(request: RightSideMenu.getUsername.Request) async
    func didTapLogOut(request: RightSideMenu.removeAcc.Request)
}

protocol RightSideMenuDataStore {
}

final class RightSideMenuInteractor: RightSideMenuDataStore {
    
    private let presenter: RightSideMenuPresentationLogic
    private let worker: RightSideMenuWorkerLogic
    
    // MARK: - Object Lifecycle
    
    init(presenter: RightSideMenuPresentationLogic, worker: RightSideMenuWorkerLogic) {
        self.presenter = presenter
        self.worker = worker
    }
}

// MARK: - BusinessLogic

extension RightSideMenuInteractor: RightSideMenuBusinessLogic {
    
    func getUsername(request: RightSideMenu.getUsername.Request) async {
        let username = await worker.getUser()
        presenter.presentUsername(response: RightSideMenu.getUsername.Response(username: username))
    }
    
    func didTapLogOut(request: RightSideMenu.removeAcc.Request) {
        worker.logOut()
    }
}
