//
//  GreetInteractor.swift
//  perhapsARedditClient
//
//  Created by a on 19.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetBusinessLogic { func saveGuest() }

class GreetInteractor: GreetBusinessLogic {
    
    private let worker: GreetWorkerLogic

    init(worker: GreetWorkerLogic) { self.worker = worker }
    
    func saveGuest() { worker.loginAsGuest() }
}
