//
//  GreetRouter.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//@objc protocol GreetRoutingLogic
//{
//  //func routeToSomewhere(segue: UIStoryboardSegue?)
//}
//
//protocol GreetDataPassing {
//  var dataStore: GreetDataStore? { get }
//}
//
//class GreetRouter: NSObject, GreetRoutingLogic, GreetDataPassing
//{
//  weak var viewController: GreetViewController?
//  var dataStore: GreetDataStore?
//
//}

protocol GreetRoutingLogic {
    func openURL(stringURL: String)
}

final class GreetRouter: GreetRoutingLogic {
    
    // MARK: - Clean Components
    
    weak var viewController: GreetViewController?
    
    // MARK: - Routing
    
    func openURL(stringURL: String) {
        if let url = URL(string: stringURL) {
          UIApplication.shared.open(url, options: [:], completionHandler: nil)
        }
    }
}
