//
//  GreetModels.swift
//  perhapsARedditClient
//
//  Created by a on 19.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Greet {
    // MARK: Use cases
    
    enum unsupportedAlert {
        
        struct Request { let alert: UIAlertController }
        
        struct Response { let alert: UIAlertController }
        
        struct ViewModel { let alert: UIAlertController }
    }
    
    enum openWebUrl {
        
        struct Request { let urlString: String }
        
        struct Response {  }
        
        struct ViewModel {  }
    }
    
    enum logIn {
        
        struct Request {  }
        
        struct Response {  }
        
        struct ViewModel {  }
    }
    
    enum skipLogin {
        
        struct Request {  }
        
        struct Response {  }
        
        struct ViewModel {  }
    }
}
