//
//  GreetRouter.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GreetRoutingLogic {
    func openURL(request: Greet.openWebUrl.Request)
    func presentMain(request: Greet.skipLogin.Request)
    func presentLogin(request: Greet.logIn.Request)
}

final class GreetRouter: GreetRoutingLogic {
    
    // MARK: - Clean Components
    
    weak var viewController: GreetViewController?
    
    // MARK: - Routing
    
    func openURL(request: Greet.openWebUrl.Request) {
        if let url = URL(string: request.urlString) {
          UIApplication.shared.open(url, options: [:], completionHandler: nil)
        }
    }
    
    func presentMain(request: Greet.skipLogin.Request) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "MainScreenViewController") as! MainScreenViewController
        vc.modalPresentationStyle = .fullScreen
        vc.modalTransitionStyle = .crossDissolve
        
        vc.config()
        
        viewController?.present(vc, animated: true, completion: nil)
    }
    
    func presentLogin(request: Greet.logIn.Request) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "LoginViewController") as! LoginViewController
        vc.modalPresentationStyle = .overFullScreen
        vc.modalTransitionStyle = .crossDissolve
        
        vc.config()
        
        viewController?.present(vc, animated: true, completion: nil)
    }
}
