////
////  LeftSideMenuInteractor.swift
////  perhapsARedditClient
////
////  Created by a on 03.09.22.
////  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
////
////  This file was generated by the Clean Swift Xcode Templates so
////  you can apply clean architecture to your iOS and Mac projects,
////  see http://clean-swift.com
////
//
//import UIKit
//
//protocol LeftSideMenuBusinessLogic
//{
//  func doSomething(request: LeftSideMenu.Something.Request)
//}
//
//protocol LeftSideMenuDataStore
//{
//  //var name: String { get set }
//}
//
//class LeftSideMenuInteractor: LeftSideMenuBusinessLogic, LeftSideMenuDataStore
//{
//  var presenter: LeftSideMenuPresentationLogic?
//  var worker: LeftSideMenuWorker?
//  //var name: String = ""
//  
//  // MARK: Do something
//  
//  func doSomething(request: LeftSideMenu.Something.Request)
//  {
//    worker = LeftSideMenuWorker()
//    worker?.doSomeWork()
//    
//    let response = LeftSideMenu.Something.Response()
//    presenter?.presentSomething(response: response)
//  }
//}
