//
//  LeftSideMenuModels.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum LeftSideMenu {
  // MARK: Use cases
  
    enum setSub {
        struct Request { let subreddit: String }
        
        struct Response {  }
        
        struct ViewModel {  }
    }
    
    enum setperiod {
        struct Request { let timePeriod: String }
        
        struct Response {  }
        
        struct ViewModel {  }
    }
}
