//
//  LeftSideMenuWorker.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LeftSideMenuWorkerLogic {
    func setSub(subreddit: String)
    func setPeriod(timePeriod: String)
}

final class LeftSideMenuWorker: LeftSideMenuWorkerLogic {
    // MARK: - Fields
    
    private var api: APIManager
    
    init(apiManager: APIManager) {
        self.api = apiManager
    }
    
    // MARK: - Methods
    
    func setSub(subreddit: String) {
        api.setUserDefaults(value: subreddit, Key: "subreddit")
    }
    func setPeriod(timePeriod: String) {
        api.setUserDefaults(value: timePeriod, Key: "timePeriod")
    }
}
