//
//  RightSideMenuViewController.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LeftSideMenuDisplayLogic {
    func dismiss()
    func updateMain()
}

final class LeftSideMenuViewController: UIViewController {
    // MARK: - Clean Components
    
    private var interactor: LeftSideMenuBusinessLogic = LeftSideMenuInteractor(worker: LeftSideMenuWorker(apiManager: APIManager()))
    private var router: LeftSideMenuRoutingLogic & LeftSideMenuDataPassing = LeftSideMenuRouter()
    
    // MARK: - config
    
    func config() {
        let apiManager = APIManager()
        let worker = LeftSideMenuWorker(apiManager: apiManager)
        let interactor = LeftSideMenuInteractor(worker: worker)
        let router = LeftSideMenuRouter()
        self.interactor = interactor
        self.router = router
        router.viewController = self
        router.viewController = self
    }
    
    // MARK: viewDidLoad

    override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    //MARK: - actions
    
    @IBAction func tap(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
    @IBAction func swipe(_ sender: Any) {
        self.dismiss(animated: true, completion: nil)
    }
    @IBAction func pics(_ sender: Any) {
        changeSub(sub: "pics")
    }
    @IBAction func photography(_ sender: Any) {
        changeSub(sub: "memes")
    }
    @IBAction func pixelart(_ sender: Any) {
        changeSub(sub: "PixelArt")
    }
    @IBAction func cat(_ sender: Any) {
        changeSub(sub: "cat")
    }

    @IBAction func day(_ sender: Any) {
        changeTimePeriod(period: "day")
    }
    @IBAction func month(_ sender: Any) {
        changeTimePeriod(period: "month")
    }
    @IBAction func year(_ sender: Any) {
        changeTimePeriod(period: "year")
    }
    @IBAction func week(_ sender: Any) {
        changeTimePeriod(period: "week")
    }
    @IBAction func all(_ sender: Any) {
        changeTimePeriod(period: "all")
    }

    //MARK: - functions
    
    func changeSub(sub: String) {
        interactor.didTapSubreddit(request: LeftSideMenu.setSub.Request(subreddit: sub))
        updateMain()
//        delegate?.redditData = nil
//        delegate?.subreddit = sub
//        delegate?.loadTableData()
//        delegate?.contractionStats = []
    }

    func changeTimePeriod(period: String) {
        interactor.didTapTimePeriod(request: LeftSideMenu.setperiod.Request(timePeriod: period))
        updateMain()
//        delegate?.redditData = nil
//        delegate?.timePeriod = period
//        delegate?.loadTableData()
//        delegate?.contractionStats = []
    }
}

// MARK: - DisplayLogic

extension LeftSideMenuViewController: LeftSideMenuDisplayLogic {
    
    func dismiss() {
        router.dismissSelf()
    }
    func updateMain() {
        NotificationCenter.default.post(name: Notification.Name("com.testCompany.Notification.reloadData"), object: nil)
    }
}
