//
//  LeftSideMenuInteractor.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LeftSideMenuBusinessLogic {
    func didTapSubreddit(request: LeftSideMenu.setSub.Request)
    func didTapTimePeriod(request: LeftSideMenu.setperiod.Request)
}

protocol LeftSideMenuDataStore {
}

final class LeftSideMenuInteractor: LeftSideMenuDataStore {
    
    private let worker: LeftSideMenuWorkerLogic
    
    // MARK: - Object Lifecycle
    
    init(worker: LeftSideMenuWorkerLogic) {
        self.worker = worker
    }
}

// MARK: - BusinessLogic

extension LeftSideMenuInteractor: LeftSideMenuBusinessLogic {
    
    func didTapSubreddit(request: LeftSideMenu.setSub.Request) {
        worker.setSub(subreddit: request.subreddit)
    }
    
    func didTapTimePeriod(request: LeftSideMenu.setperiod.Request) {
        worker.setPeriod(timePeriod: request.timePeriod)
    }
}
