//
//  LeftSideMenuPresenter.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

//import UIKit
//
//protocol LeftSideMenuPresentationLogic
//{
//  func presentSomething(response: LeftSideMenu.Something.Response)
//}
//
//class LeftSideMenuPresenter: LeftSideMenuPresentationLogic
//{
//  weak var viewController: LeftSideMenuDisplayLogic?
//  
//  // MARK: Do something
//  
//  func presentSomething(response: LeftSideMenu.Something.Response)
//  {
//    let viewModel = LeftSideMenu.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
//}
