//
//  MainScreenRouter.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScreenRoutingLogic {
    func navigateToRightSide()
    func navigateToLeftSide()
    func popupShareMenu(urlString: String)
    func popupCommentsView(permalinkComponent: String)
}

protocol MainScreenDataPassing {  }

final class MainScreenRouter: MainScreenRoutingLogic, MainScreenDataPassing {
    // MARK: - Clean Components
    
    weak var viewController: MainScreenViewController?

    // MARK: - Routing
    
    func navigateToRightSide() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "RightSideMenuViewController") as! RightSideMenuViewController
        vc.modalPresentationStyle = .overFullScreen
        vc.modalTransitionStyle = .crossDissolve
        
        vc.config()
        
        viewController?.present(vc, animated: true, completion: nil)
    }
    func navigateToLeftSide() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "LeftSideMenuViewController") as! LeftSideMenuViewController
        vc.modalPresentationStyle = .overFullScreen
        vc.modalTransitionStyle = .crossDissolve
        
        vc.config()
        
        viewController?.present(vc, animated: true, completion: nil)
    }
    func popupShareMenu(urlString: String) {
        let vc = UIActivityViewController(activityItems: ["Check this out! \(urlString)"], applicationActivities: nil)
        vc.popoverPresentationController?.sourceView = viewController?.view
        
        viewController?.present(vc, animated: true, completion: nil)
    }
    func popupCommentsView(permalinkComponent: String) {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "CommentsViewController") as! CommentsViewController
        vc.modalPresentationStyle = .overFullScreen
        vc.modalTransitionStyle = .coverVertical
        vc.commentUrlString = "https://www.reddit.com\(permalinkComponent).json"
        
        vc.config()
        viewController?.present(vc, animated: true, completion: nil)
    }
}
