//
//  MainScreenRouter.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScreenRoutingLogic {
    func navigateToRightSide()
    func navigateToLeftSide()
}

protocol MainScreenDataPassing {  }

final class MainScreenRouter: MainScreenRoutingLogic, MainScreenDataPassing {
    // MARK: - Clean Components
    
    weak var viewController: MainScreenViewController?

    // MARK: - Routing
    
    func navigateToRightSide() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "RightSideMenuViewController") as! RightSideMenuViewController
        vc.modalPresentationStyle = .overFullScreen
        vc.modalTransitionStyle = .flipHorizontal
        
        vc.config()
        
        viewController?.present(vc, animated: true, completion: nil)
    }
    func navigateToLeftSide() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let vc = storyboard.instantiateViewController(identifier: "leftSideMenuViewController") as! LeftSideMenuViewController
        vc.modalPresentationStyle = .overFullScreen
        vc.modalTransitionStyle = .flipHorizontal
        
        vc.config()
        
        viewController?.present(vc, animated: true, completion: nil)
    }
}
