//
//  MainScreenRouter.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScreenRoutingLogic {
    func navigateToRightSide()
    func navigateToLeftSide()
}

protocol MainScreenDataPassing {
    var username: String { get }
}

final class MainScreenRouter: MainScreenRoutingLogic, MainScreenDataPassing {
    // MARK: - Clean Components
    
    weak var viewController: MainScreenViewController?
    var username: String
    
    // MARK: - Object Lifecycle
    
    init(username: String) {
        self.username = username
    }
    
    // MARK: - Routing
    
    func navigateToRightSide() {
//        guard let selectedCountry = dataStore.selectedCountry else { return }
//        let destinationVC = CountryDetailsConfigurator.configure(with: selectedCountry)
//        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
    }
    func navigateToLeftSide() {
        
    }
}
