//
//  MainScreenInteractor.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainScreenBusinessLogic {
    func getPosts(request: MainScreen.GetPosts.Request)
    func refreshHiddenPostData(request: MainScreen.refreshHiddenPost.Request)
    func tableLoadImageOrGif(urlString: String) async -> UIImage?
    func getUIimageDimentions(urlString: String) -> [CGFloat]
    func getVideoResolution(url: String) -> [CGFloat]
//    func didTapPost(request: MainScreen.hidePost.Request)
}

protocol MainScreenDataStore {
//    var selectedCountry: Country? { get }
}

final class MainScreenInteractor: MainScreenDataStore {
    private let presenter: MainScreenPresentationLogic
    private let worker: MainScreenWorkerLogic
    
    var redditPosts: RedditPosts? = nil
    private var iconURLStrings: [String] = []
//    private(set) var selectedCountry: Country?
    
    // MARK: - Object Lifecycle
    
    init(presenter: MainScreenPresentationLogic, worker: MainScreenWorkerLogic) {
        self.presenter = presenter
        self.worker = worker
    }
}

// MARK: - BusinessLogic

extension MainScreenInteractor: MainScreenBusinessLogic {

//    func didTapPost(request: MainScreen.hidePost.Request) {
//        self.selectedCountry = countries.first { $0.latlng == request.coord}
//        presenter.presentSelectedCountry(response: Table.ShowCountryDetails.Response())
//    }
    
    func getPosts(request: MainScreen.GetPosts.Request) {
        Task {
            do {
                let redditPosts = try await worker.fetchPosts(after: nil)
                let hiddenPosts = await worker.getHiddenPosts()
                for i in 0..<redditPosts.data.children.count {
                    let subreddit = redditPosts.data.children[i].data.subreddit
                    iconURLStrings += [await worker.getIconUrl(from: subreddit)]
                }
                DispatchQueue.main.async { [weak self] in
                    self?.presenter.presentPosts(response: MainScreen.GetPosts.Response(data: redditPosts, hiddenPosts: hiddenPosts, iconUrlStrings: self?.iconURLStrings ?? []))
                }
            } catch { print(error) }
        }
    }
    
    func refreshHiddenPostData(request: MainScreen.refreshHiddenPost.Request) {
        Task {
            let hiddenPosts = await worker.getHiddenPosts()
            presenter.refreshHiddenPosts(response: MainScreen.refreshHiddenPost.Response(posts: hiddenPosts))
        }
        
    }
    
    func tableLoadImageOrGif(urlString: String) async -> UIImage? {
        let isPicture = urlString.contains(".jpg") || urlString.contains("png")
        let isGif = urlString.contains(".gif") && !urlString.contains(".gifv")
        
        if isGif {
            do {
                return try await worker.loadGifFrom(urlString: urlString)
            } catch { print("gifError") }
        }
        if isPicture {
            do {
                return try await worker.loadImageFrom(urlString: urlString)
            } catch { print("gifError") }
        }
        return UIImage(named: "loadingError")
    }
    
    func getUIimageDimentions(urlString: String) -> [CGFloat] {
        worker.getUIimageDimentions(urlString: urlString)
    }
    
    func getVideoResolution(url: String) -> [CGFloat] {
        worker.getVideoResolution(url: url)
    }
//    func getMorePosts() {
//
//    }
}
