//
//  CommentsInteractor.swift
//  perhapsARedditClient
//
//  Created by a on 19.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentsBusinessLogic {
    func getComments(request: Comments.getComments.Request)
}

protocol CommentsDataStore {
}

final class CommentsInteractor: CommentsDataStore {
    
    private let presenter: CommentsPresentationLogic
    private let worker: CommentsWorkerLogic
    
    // MARK: - Object Lifecycle
    
    init(presenter: CommentsPresentationLogic, worker: CommentsWorkerLogic) {
        self.presenter = presenter
        self.worker = worker
    }
}

// MARK: - BusinessLogic

extension CommentsInteractor: CommentsBusinessLogic {
    
    func getComments(request: Comments.getComments.Request) {
        let urlString = request.urlString
        Task {
            do {
                let commentsPage = try await worker.fetchComments(urlString: urlString)
                DispatchQueue.main.async { [weak self] in
                    self?.presenter.presentPosts(response: Comments.getComments.Response(commentsPageComponents: commentsPage))
                }
            } catch { print(error) }
        }
    }
    
}

