//
//  CommentsModels.swift
//  perhapsARedditClient
//
//  Created by a on 19.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Comments {
    // MARK: Use cases
    
    enum dismiss {
        struct Request {  }

        struct Response {  }

        struct ViewModel {  }
    }
    
    enum getComments {
        struct Request { let urlString: String }
        
        struct Response { let commentsPageComponents: [CommentsPageComponent] }
        
        struct ViewModel { let commentForTable: [CommentForTable] }
    }
}
