//
//  CommentsRouter.swift
//  perhapsARedditClient
//
//  Created by a on 19.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentsRoutingLogic {
    func dismissSelf()
}

protocol CommentsDataPassing { }

final class CommentsRouter: CommentsRoutingLogic, CommentsDataPassing {
    // MARK: - Clean Components
    
    weak var viewController: CommentsViewController?

    // MARK: - Routing
    
    func dismissSelf() {
        viewController?.dismiss(animated: true, completion: nil)
    }
}
