//
//  CommentsWorker.swift
//  perhapsARedditClient
//
//  Created by a on 19.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CommentsWorkerLogic {
    func fetchComments(urlString: String) async throws -> [CommentsPageComponent]
}

final class CommentsWorker: CommentsWorkerLogic {
    // MARK: - Fields
    
    private var api: APIManager
    
    init(apiManager: APIManager) {
        self.api = apiManager
    }
    
    // MARK: - Methods
    
    func fetchComments(urlString: String) async throws -> [CommentsPageComponent] {
        return try await api.fetchData(urlString: urlString, decodingType: [CommentsPageComponent].self)
    }
    
}
