//
//  LoginWorker.swift
//  perhapsARedditClient
//
//  Created by a on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginWorkerLogic {
    func login(username: String, password: String) -> Bool
    func register(username: String, password: String) -> Bool
}

final class LoginWorker: LoginWorkerLogic {
    // MARK: - Fields
    
    private var api: APIManager
    
    init(apiManager: APIManager) {
        self.api = apiManager
    }
    
    // MARK: - Methods
    
    func login(username: String, password: String) -> Bool {
        api.KeyChainGetAccess(username: username, password: password)
    }
    func register(username: String, password: String) -> Bool {
        api.keyChainSave(username: username, passcode: password)
    }
}
